# docker-compose.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/inventory.db:/app/inventory.db
    environment:
      - DATABASE_URL=/app/inventory.db