version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/inventory.db:/app/inventory.db
    environment:
      - DATABASE_URL=/app/inventory.db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "tests/test_main.py", "-v"]
    volumes:
      - .:/app
      - ./app/inventory.db:/app/inventory.db
    environment:
      - DATABASE_URL=/app/inventory.db