# .github/workflows/ci.yml
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build & Run Tests
        run: |
          docker-compose build
          docker-compose up --abort-on-container-exit --exit-code-from test